project:
  type: website
  
website:
  title: "Saoirse Kelleher"
  resources:
    - CNAME
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

