project:
  type: website
  resources:
    - CNAME
  
website:
  title: "Saoirse Kelleher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - CV.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

