project:
  type: website
  resources:
    - CNAME
  
website:
  title: "Saoirse Kelleher"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - Research.qmd
      - href: CV.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/SaoirseKelleher
        aria-label: GitHub
      - icon: envelope
        href: saoirse.kelleher@student.unimelb.edu.au
        aria-label: Email
  page-footer:
    background: light
    left: Copyright Saoirse Kelleher 2024
    right: This website built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

